name: AspiredMC Jetbrains Workspace

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}  
        password: ${{ secrets.GITHUB_TOKEN }} 

    - name: Build the Docker image
      id: build
      run: |
        IMAGE_NAME=ghcr.io/aspiredmc/jetbrains-workspace
        TIMESTAMP=$(date +%s)
        
        docker build . --file Dockerfile --tag ${IMAGE_NAME}:latest
        
        docker tag ${IMAGE_NAME}:latest ${IMAGE_NAME}:${TIMESTAMP}
        
        echo "::set-output name=latest_tag::${IMAGE_NAME}:latest"
        echo "::set-output name=timestamp_tag::${IMAGE_NAME}:${TIMESTAMP}"

    - name: Push Docker image to GitHub Packages
      run: |
        IMAGE_NAME=ghcr.io/aspiredmc/jetbrains-workspace
        
        docker push ${IMAGE_NAME}:latest
        
        TIMESTAMP_TAG=${{ steps.build.outputs.timestamp_tag }}
        docker push ${TIMESTAMP_TAG}
