name: AspiredMC Jetbrains Workspace

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}  # Use the GitHub username or organization name
        password: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token for authentication

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/AspiredMC/jetbrains-workspace:latest
        docker tag ghcr.io/AspiredMC/jetbrains-workspace:latest ghcr.io/AspiredMC/jetbrains-workspace:$(date +%s)

    - name: Push Docker image to GitHub Packages
      run: |
        docker push ghcr.io/AspiredMC/jetbrains-workspace:latest
        docker push ghcr.io/AspiredMC/jetbrains-workspace:$(date +%s)
